spring.application.name=auth-server
# Cau hinh port
# Resource Server => 8080
# Auth Server => 8081
server.port=8081

# Cau hinh Auth Server

# Issuer
spring.security.oauth2.authorizationserver.issuer=http://auth-server.vn:8081

# Client 1 registration 'feclient'
spring.security.oauth2.authorizationserver.client.feclient.registration.client-id=feclient
#spring.security.oauth2.authorizationserver.client.feclient.registration.client-secret={noop}feclient-secret
# Can mã hoá lun client-secret vì Spring se gui Bean PasswordEncoder de so sánh secret
# Neu không phai thuc hien cau hình sâu trong Bean PasswordEncoder
# {noop}feclient-secret -> $2a$12$HuqjDD673fZgz9/mD4FOr.5J0IDbVxnDAvIJHH2UEi849oMSjoiYG
spring.security.oauth2.authorizationserver.client.feclient.registration.client-secret=$2a$12$HuqjDD673fZgz9/mD4FOr.5J0IDbVxnDAvIJHH2UEi849oMSjoiYG
spring.security.oauth2.authorizationserver.client.feclient.registration.client-authentication-methods=client_secret_basic,client_secret_post
spring.security.oauth2.authorizationserver.client.feclient.registration.authorization-grant-types=authorization_code,refresh_token
spring.security.oauth2.authorizationserver.client.feclient.registration.redirect-uris=https://oauth.pstmn.io/v1/callback,http://localhost:8080
spring.security.oauth2.authorizationserver.client.feclient.registration.scopes=openid,profile,email,artists.read,artists.write

# Client X reg
#spring.security.oauth2.authorizationserver.client.mobileAppClient.registration.client-id=appclient

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=sba301_authserver;encrypt=false;
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.hbm2ddl.auto=update
# create -> tao các bang theo thông tin tu @Entity
# create-drop -> tuong tu nhung se xoá khi app dung
# none -> ko làm gì (DB first approach)
# Thông thuong khi moi khoi tao du án theo code-first -> chon create-drop
# DB on dinh roi -> chuyen ve create/update -> none

# 1 so log level de debug
logging.level.org.springframework.security=DEBUG
